# 논리적 분리를 위한 Namespace (요구사항 9.3 / 10 / 11)
apiVersion: v1
kind: Namespace
metadata:
  name: wsc
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
